[tool.ruff]
line-length = 500
ignore-init-module-imports = true
ignore = ['F401']
include = ['src/**/*.py']
exclude = ['scripts/*']

[tool.black]
line-length = 120
target-version = ['py37', 'py38']


[tool.jupytext]
formats = "ipynb,py:percent"